### ISSUE TITLE
About that assembly-level UserSecretsId attribute

### ISSUE THREAD

**Issue by mderriey** [staff0rd/coach_bags#1]
I did some research after you said [in a tweet](https://twitter.com/staff0rd/status/1284404037052293123) that you had the `UserSecretsId` MSBuild property in the `.csproj` file but the assembly-level attribute wasn't generated.

### A few tests

Here a few quick tests I did, and the outcome regarding the presence of the `UserSecretsId` attribute in the resulting assembly.
All those tests were performed after removing [the explicit assembly-level attribute](https://github.com/staff0rd/coach_bags/blob/a8f011d2d0920127ec9e1a039bf5e0baf49301f3/src/Scraper/Program.cs#L22), but leaving the [MSBuild property in the `.csproj`](https://github.com/staff0rd/coach_bags/blob/a8f011d2d0920127ec9e1a039bf5e0baf49301f3/src/Scraper/coach_bags_selenium.csproj#L6).

|Test|Outcome|
|-|-|
|No changes|❌ No assembly-level attribute present|
|Add an explicit reference to `Microsoft.Extensions.Configuration.UserSecrets`|✔ Assembly-level attribute present|
|Update the SDK to `Microsoft.NET.SDK.Web`|✔ Assembly-level attribute present|
|Add a framework reference to `Microsoft.AspNetCore.App`|✔ Assembly-level attribute present|

### Why though?!

After digging a bit more, I found 2 places where the assembly-level attribute is generated:

1. The [`Microsoft.NET.Sdk.FrameworkReferenceResolution.targets`](https://github.com/dotnet/sdk/blob/80fe95f739ed59e3d653e68999acc5f9c05ca07f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets#L348-L365) file, part of the .NET Core SDK; and
1. The [`Microsoft.Extensions.Configuration.UserSecrets.targets`](https://github.com/dotnet/extensions/blob/3dc5e9a24865ab84fce6fc078fce4bd7cfcab5c7/src/Configuration/Config.UserSecrets/src/build/netstandard2.0/Microsoft.Extensions.Configuration.UserSecrets.targets#L8-L12), part of the `Microsoft.Extensions.Configuration.UserSecrets` NuGet package.

#### Test 1 &mdash; No changes

In that test, only the .NET Core SDK `.targets` file is executed as there's no direct reference to the `Microsoft.Extensions.Configuration.UserSecrets` package; there is, however, an indirect one through `Microsoft.Extensions.Hosting`, which allows you to use the `.AddUserSecrets<T>` method.

The [condition necessary to add the attribute](https://github.com/dotnet/sdk/blob/80fe95f739ed59e3d653e68999acc5f9c05ca07f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets#L359-L361) evaluates to false, as the project doesn't have a `FrameworkReference` to `Microsoft.AspNetCoreApp`, and there's no direct reference to `Microsoft.Extensions.Configuration.UserSecrets`.

#### Test 2 &mdash; Add an explicit reference to `Microsoft.Extensions.Configuration.UserSecrets`

In that case, both the `targets` files are imported during the build.

The one from the `Microsoft.Extensions.Configuration.UserSecrets` NuGet package first creates the assembly-level attribute, while the one from the .NET SDK doesn't as by the time it executes, there's already one; see the [first clause of the condition](https://github.com/dotnet/sdk/blob/80fe95f739ed59e3d653e68999acc5f9c05ca07f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets#L359).

#### Test 3 &mdash; Update the SDK to `Microsoft.NET.SDK.Web`

Using the `Microsoft.NET.SDK.Web` SDK implicitly adds a framework reference to `Microsoft.AspNetCore.App` as per [the official documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio#use-the-aspnet-core-shared-framework), specifically:

> As of .NET Core 3.0, projects using the Microsoft.NET.Sdk.Web MSBuild SDK implicitly reference the shared framework.

Since there's no direct reference to `Microsoft.Extensions.Configuration.UserSecrets`, its `.targets` file is not imported during the build.

However, the one from the .NET SDK is, and `@(FrameworkReference->WithMetadataValue('Identity', 'Microsoft.AspNetCore.App')->Count()) != 0` (see [here](https://github.com/dotnet/sdk/blob/80fe95f739ed59e3d653e68999acc5f9c05ca07f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets#L360)) evaluates to `true`, which results in the assembly-level attribute being added.

#### Test 4 &mdash; Add a framework reference to `Microsoft.AspNetCore.App`

This test is similar to the previous one, at least in the reason why the `[UserSecretsId]` attribute is created, as we explicitly add a reference to the shared framework, while the previous added it implicitly.

### Conclusion

The code doesn't call `.AddUserSecrets<T>`, so it really makes no difference 😅, but hopefully that was useful or interesting?

One question that I then have is, when would you create a .NET Core console app and **not** reference the shared framework? It brings in a bunch of additional packages that you then don't have to manage.

**Comment by staff0rd** [comment]
I was going to blog about this, but now you've done most of the work it looks like you have to :)

Anyhow,
> The code doesn't call .AddUserSecrets<T>, so it really makes no difference

But it does because i'm using `CreateDefaultBuilder` which in [dev calls `AddUserSecrets`](https://github.com/dotnet/runtime/blob/f4e9146d1d2ba7cf48ab59022658619fc9dbaec3/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L79-L86) and [here](https://github.com/dotnet/runtime/blob/f4e9146d1d2ba7cf48ab59022658619fc9dbaec3/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/UserSecretsConfigurationExtensions.cs#L132) is where `AddUserSecrets` checks for the presence of the attribute.

It seems we're not the first also;

* [dotnet/extensions/2743](https://github.com/dotnet/extensions/issues/2743)
* [dotnet/sdk/4007](https://github.com/dotnet/sdk/issues/4007)

Both suggest the workaround is calling `AddUserSecrets` yourself, but why should I if I just pop the assembly attribute in?

**Comment by staff0rd** [comment]
> One question that I then have is, when would you create a .NET Core console app and not reference the shared framework?

Do you mean in this case, or in general? The existing csproj is simply the result of `dotnet new console`, with `UserSecretsId` appearing because of `dotnet user-secrets init`.

**Comment by mderriey** [comment]
> But it does because i'm using CreateDefaultBuilder which in dev calls AddUserSecrets and here is where AddUserSecrets checks for the presence of the attribute.

Ah yes! I thought it was added when calling `ConfigureWebHostDefaults`.

> I was going to blog about this, but now you've done most of the work it looks like you have to :)

I won't, please go ahead!

> Do you mean in this case, or in general? The existing csproj is simply the result of dotnet new console, with UserSecretsId appearing because of dotnet user-secrets init.

In general, as I can't see a negative impact of adding it.
Maybe for self-contained apps?

**Comment by mderriey** [comment]
> Both suggest the workaround is calling AddUserSecrets yourself, but why should I if I just pop the assembly attribute in?

If you add the attribute yourself, then there's no need to explicitly call `AddUserSecrets` if my understanding is correct.
